title: "Quaint Beach Town Rental"
description: "A cozy short-term rental near the Jersey beach, perfect for a relaxing getaway."
baseurl: "dkosoi.github.io"
url: "dkosoi.github.io/shorehouse"
theme: minima
